### PR TITLE
Start server, find executables

### PR DESCRIPTION
**Pull request by nwolverson**
For #10 

Server start code is the version that went from me via @kRITZCREEK, you can tell by the funny characters... Given the discussion about multiple instances, automatically finding a port etc. it might be nice to have that here too.

### CODE REVIEW

**Comment by anttih** [comment]
`startServer` is working for me 👍

**Comment by kritzcreek** [comment]
Great we'll take it then! thanks ;)

**Comment by kritzcreek** [comment]
I'll release this as it is and we can worry about multiple instances later? Is 2.1.0 fine? I'll add a package.json file to pull in the node dependency

**Comment by nwolverson** [comment]
Great. I don't think the package.json is particularly meaningful though as this is installed as a bower dependency of a client project, you need to add it to the package.json of that project...

It would be of use if I had bothered to add an integration test.

**Comment by kritzcreek** [comment]
The idea is to make it easier to contribute to `purescript-psc-ide`

**Pull request merged**
