### PR TITLE
Fix which callback

### PR DESCRIPTION
**Pull request by nwolverson**
Succeeding also when you fail is bad and confusing.

### CODE REVIEW

**Comment by kritzcreek** [comment]
Node callbacks are such a Joy aren't they? Who thought that would be a good idea?

**Comment by kritzcreek** [comment]
Will Release as 5.0.1 once I get at my Laptop

**Comment by kritzcreek** [comment]
done!

**Comment by nwolverson** [comment]
Cheers, if only I could say this was the first time I made such a mistake. Or 2nd, 3rd, 4th, ....

**Comment by kritzcreek** [comment]
It's just broken by design

**Comment by nwolverson** [comment]
I have the same issue with any async primitives I think. Like constructing promises, I guess anything with continuations. Confuse the intention of calling the callback ("return a value") with the actual current control flow.

**Pull request merged**
