### PR TITLE
Start server with args

### PR DESCRIPTION
**Pull request by nwolverson**
(This is on top of the position info change)

Thoughts on `startServer` overloads?

### CODE REVIEW

**Comment by kritzcreek** [comment]
Since we already have a configuration object, I think we should extend it to also take the STDIOBehaviour and exe path. I think the only three current users are you, @anttih and me, so I'd prefer to go for a clean API and accept breaking changes.

**Comment by kritzcreek** [comment]
I rebased instead of merging on master, so you'll have to rebase this one aswell, sry..

**Comment by nwolverson** [comment]
Sure, I was thinking of it as an object representing the arguments in a typed way - but no real reason to do so.

Do you think we should just go with a single `startServer` taking such an object?

**Comment by kritzcreek** [comment]
@nwolverson exactly, and have the default behaviour for ' and '' inside the default configuration object

**Comment by kritzcreek** [comment]
sold!

**Comment by nwolverson** [comment]
Thanks :+1:

**Pull request merged**
