### PR TITLE
accumulate data and fire on end

### PR DESCRIPTION
**Pull request by nwolverson**
For #4.

I know you mentioned some kind of race condition, but I think `end` was the suggested event I saw and this seems to work for me, and avoid the issues in #4.

### CODE REVIEW

**Comment by kritzcreek** [comment]
If it works for you that's allright. I'll see if it pops up again.

**Comment by nwolverson** [comment]
Thanks! Would you mind tagging a release?

**Comment by kritzcreek** [comment]
1.1.0 released :)

**Comment by nwolverson** [comment]
Thanks! Using this in atom integration now.

**Pull request merged**
